#spring:
#  application:
#    name: e-police-system
#server:
#  port: 9080
#eureka:
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 20
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.10.11:8761/eureka